# Fixed seed set for reproduction (middle 10 seeds).
# Source: SWA acc in results_30seeds_SWA.txt sorted, drop 10 worst + 10 best, keep middle 10.
# Used by paper reproduction / ablation / sensitivity analysis.
# Auto-generated by analyze_30seeds_trim.py; do not edit by hand.
REPRO_SEEDS = [5, 28, 19, 21, 7, 20, 15, 18, 30, 3]
